# 2. Data wrangling<a id='2_Data_wrangling'></a> - Electric Vehicles Adoption Rate

## 2.1 Contents<a id='2.1_Contents'></a>
* [2 Data wrangling](#2_Data_wrangling)
  * [2.1 Contents](#2.1_Contents)
  * [2.2 Introduction](#2.2_Introduction)
    * [2.2.1 Recap Of Data Science Problem](#2.2.1_Recap_Of_Data_Science_Problem)
    * [2.2.2 Datasets Used](#2.2.2_Datasets_Used)
  * [2.3 Imports](#2.3_Imports)
  * [2.4 Objectives](#2.4_Objectives)
  * [2.5 Load & Explore Datasets](#2.5_Load_&_Explore_Datasets)
    * [2.5.1 Electric Vehicles Dataset](#2.5.1_Electric_Vehicles_Dataset)
    * [2.5.2 All Vehicle Registration Dataset](#2.5.2_All_Vehicle_Registration_Dataset)
    * [2.5.3 Socioeconomic & Charging Stations Support Dataset](#2.5.3_Socioeconomic_&_Charging_Stations_Support_Dataset)
  * [2.6 Merge All Datasets](#2.6_Merge_All_Datasets) 
  * [2.7 Save The Data](#2.7_Save_The_Data)
  * [2.8 Summary](#2.8_Summary)

## 2.2 Introduction<a id='2.2_Introduction'></a>

### 2.2.1 Recap Of Data Science Problem<a id='2.2.1_Recap_Of_Data_Science_Problem'></a>

Electric Vehicle adoption has been growing significantly in the USA for the past decade. However, adoption is very uneven across different regions. Some have seen rapid adoption rates while others lag behind despite being in the same state.

The variation suggests that multiple factors such as socioeconomic, technology and policy incentives might be at play here and this project intends to explore their influence and how these factors interact with each other to drive adoption rates at region level.

Our objective is to develop a data-driven framework to quantify EV adoption at the county level and identify the key drivers influencing it. Using Washington state as a case study, the project constructs adoption rate as the proportion of electric vehicle registration to total passenger vehicle registration at the county year granularity.

The ultimate goal of the project is to provide actionable insights to help prioritize regions for EV infrastructure such as charging stations and incentives.

### 2.2.2 Datasets Used<a id='2.2.2_Datasets_Used'></a>

In this data wrangling step, data from the following key data sources for Washington State has been used.

1) Electric Vehicles Data : https://data.wa.gov/Transportation/Electric-Vehicle-Population-Data/f6w7-q2d2/about_data</p>
2) All Vehicle Registrations : https://data.wa.gov/Transportation/Vehicle-Registrations-by-Class-and-County/hmzg-s6q4/about_data </p>
3) Median Income : https://ofm.wa.gov/data-research/economy/median-household-income-estimates/</p>
4) Population : https://ofm.wa.gov/data-research/population-demographics/estimates/april-1-official/, https://ofm.wa.gov/data-research/population-demographics/estimates/archive/</p>
5) EV Charging Stations Data : https://ev-map-wsdot.hub.arcgis.com/apps/7e310dcd476640ec8c611c101f610c09/explore</p>

The median income, population & electric charging stations data has already been premerged into one csv file.

This step will involve cleansing, restructuring, reformating and narrowing down of datasets as needed to get a consistent and reliable dataset. The datasets will then be merged into a single dataset and validation checks will be done to make sure the final data is ready for Exploratory Data Analysis phase.

## 2.3 Imports<a id='2.3_Imports'></a>

In [1]:
#Import all relevant packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from library.sb_utils import save_file
import requests

## 2.4 Objectives<a id='2.4_Objectives'></a>

* Ensuring all data points needed are available to answer the problem
    * Identification of the required target value
    * Identification and creation of potentially useful features for predictive modeling
* Making sure there are no fundamental issues with the data

## 2.5 Load & Explore Datasets <a id='2.5_Load_&_Explore_Datasets'></a>

### 2.5.1 Electric Vehicles Dataset<a id='2.5.1_Electric_Vehicles_Dataset'></a>

In [2]:
# import county year grain electric vehicle population data csv file
ev_data = pd.read_csv('../data/raw/Electric_Vehicle_Population_Data.csv')

In [3]:
ev_data.shape

(285822, 16)

In [4]:
ev_data.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,1N4AZ1CPXL,King,Shoreline,WA,98133.0,2020,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,149.0,32.0,237906875,POINT (-122.33364 47.73709),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303302e+10
1,ZACPDFDW6R,Kitsap,Bremerton,WA,98311.0,2024,DODGE,HORNET,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,32.0,23.0,267257532,POINT (-122.60915 47.62631),PUGET SOUND ENERGY INC,5.303509e+10
2,5YJYGDEE5L,King,Bellevue,WA,98004.0,2020,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,291.0,48.0,114986196,POINT (-122.1872 47.61001),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10
3,JTMABACA0R,King,Seattle,WA,98178.0,2024,TOYOTA,BZ4X,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,37.0,267472859,POINT (-122.25031 47.49481),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
4,WBY2Z2C54E,King,Bellevue,WA,98004.0,2014,BMW,I8,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,14.0,41.0,205545868,POINT (-122.1872 47.61001),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10

In [5]:
ev_data.describe(include='all')

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
count,285822,285812,285812,285822,285812.000000,285822.000000,285822,285822,285822,285822,285814.000000,285089.000000,2.858220e+05,285804,285812,2.858120e+05
unique,17517,254,918,51,NaN,NaN,48,194,2,3,NaN,NaN,NaN,1158,77,NaN
top,7SAYGDEE7P,King,Seattle,WA,NaN,NaN,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,NaN,NaN,NaN,POINT (-122.13158 47.67858),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),NaN
freq,1210,140181,43876,285090,NaN,NaN,117392,62154,229876,184287,NaN,NaN,NaN,6918,101184,NaN
mean,NaN,NaN,NaN,NaN,98174.396446,2022.166107,NaN,NaN,NaN,NaN,38.150808,28.803619,2.479260e+08,NaN,NaN,5.296827e+10
std,NaN,NaN,NaN,NaN,2616.358934,3.067272,NaN,NaN,NaN,NaN,77.427183,14.907337,6.299283e+07,NaN,NaN,1.678669e+09
min,NaN,NaN,NaN,NaN,1030.000000,1999.000000,NaN,NaN,NaN,NaN,0.000000,1.000000,4.385000e+03,NaN,NaN,1.001020e+09
25%,NaN,NaN,NaN,NaN,98052.000000,2021.000000,NaN,NaN,NaN,NaN,0.000000,17.000000,2.246175e+08,NaN,NaN,5.303301e+10
50%,NaN,NaN,NaN,NaN,98133.000000,2023.000000,NaN,NaN,NaN,NaN,0.000000,32.000000,2.649833e+08,NaN,NaN,5.303303e+10
75%,NaN,NaN,NaN,NaN,98383.000000,2024.000000,NaN,NaN,NaN,NaN,32.000000,42.000000,2.812755e+08,NaN,NaN,5.305394e+10
max,NaN,NaN,NaN,NaN,99517.000000,2027.000000,NaN,NaN,NaN,NaN,337.000000,49.000000,4.791150e+08,NaN,NaN,6.601095e+10

In [6]:
#Quick summary of the dataset
ev_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 285822 entries, 0 to 285821
Data columns (total 16 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   VIN (1-10)                                         285822 non-null  object
 1   County                                             285812 non-null  object
 2   City                                               285812 non-null  object
 3   State                                              285822 non-null  object
 4   Postal Code                                        285812 non-null  float64
 5   Model Year                                         285822 non-null  int64
 6   Make                                               285822 non-null  object
 7   Model                                              285822 non-null  object
 8   Electric Vehicle Type                              285822 non-null  object
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  285822 non-null  object
 10  Electric Range                                     285814 non-null  float64
 11  Legislative District                               285089 non-null  float64
 12  DOL Vehicle ID                                     285822 non-null  int64
 13  Vehicle Location                                   285804 non-null  object
 14  Electric Utility                                   285812 non-null  object
 15  2020 Census Tract                                  285812 non-null  float64
dtypes: float64(4), int64(2), object(10)
memory usage: 34.9+ MB

First we will filter for EVs in Washington State by only keep state=WA.

In [7]:
ev_data=ev_data[ev_data['State']=='WA']

In [8]:
#Check for null value columns and recordcount
ev_data.isnull().sum().sort_values(ascending=False)

Vehicle Location                                     8
Electric Range                                       8
Legislative District                                 1
VIN (1-10)                                           0
Postal Code                                          0
County                                               0
City                                                 0
State                                                0
Model                                                0
Make                                                 0
Model Year                                           0
Clean Alternative Fuel Vehicle (CAFV) Eligibility    0
Electric Vehicle Type                                0
DOL Vehicle ID                                       0
Electric Utility                                     0
2020 Census Tract                                    0
dtype: int64

In [9]:
#Let's look at the fields with most missing values
ev_data[ev_data['Vehicle Location'].isna()]

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
165737,JTDKARFP1H,Pacific,Long Beach,WA,98634.0,2017,TOYOTA,PRIUS PRIME (PHEV),Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25.0,19.0,171247282,NaN,BONNEVILLE POWER ADMINISTRATION||PUD NO 2 OF P...,5.304995e+10
191580,1C4JJXP69P,Pacific,Long Beach,WA,98634.0,2023,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,21.0,19.0,254934886,NaN,BONNEVILLE POWER ADMINISTRATION||PUD NO 2 OF P...,5.304995e+10
194606,7SAYGDEE0N,Pacific,Long Beach,WA,98634.0,2022,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,19.0,211479649,NaN,BONNEVILLE POWER ADMINISTRATION||PUD NO 2 OF P...,5.304995e+10
199508,7PDSGABA9R,Pacific,Long Beach,WA,98634.0,2024,RIVIAN,R1S,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,19.0,261660878,NaN,BONNEVILLE POWER ADMINISTRATION||PUD NO 2 OF P...,5.304995e+10
203330,1G1FW6S08N,Pacific,Long Beach,WA,98634.0,2022,CHEVROLET,BOLT EV,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,19.0,218102209,NaN,BONNEVILLE POWER ADMINISTRATION||PUD NO 2 OF P...,5.304995e+10
206933,3GN7DLRPXS,Pacific,Long Beach,WA,98634.0,2025,CHEVROLET,EQUINOX,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,19.0,276815332,NaN,BONNEVILLE POWER ADMINISTRATION||PUD NO 2 OF P...,5.304995e+10
218864,1FTVW3LU7S,Pacific,Long Beach,WA,98634.0,2025,FORD,F-150,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,19.0,282544286,NaN,BONNEVILLE POWER ADMINISTRATION||PUD NO 2 OF P...,5.304995e+10
279643,KMHE54L2XH,Pacific,Long Beach,WA,98634.0,2017,HYUNDAI,SONATA,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,27.0,19.0,245533578,NaN,BONNEVILLE POWER ADMINISTRATION||PUD NO 2 OF P...,5.304995e+10

1. None of these missing vehicle locations are in Washington State. Also, we do not need Vehicle Location field as we already have geographical location in terms of City, County and Postal code so we will drop this column entirely
2. 2020 Census Tract Field per our data source info. represents a combination of the state, county, and census tract codes as assigned by the United States Census Bureau in the 2020 census, also known as Geographic Identifier (GEOID). We will not need this data since we already have the geographical data.
3. We will also drop Legislative District field as it represents political boundaries and we do not intend to use this data for this project.

In [10]:
ev_data =ev_data.drop(columns=['Legislative District','Vehicle Location','2020 Census Tract'])

Let's look at electric range missing values next.

In [11]:
ev_data[ev_data['Electric Range'].isna()]

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,DOL Vehicle ID,Electric Utility
4708,ZHWUC1ZM5S,King,Seattle,WA,98125.0,2025,LAMBORGHINI,REVUELTO,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,NaN,282538896,CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)
97459,ZHWUC1ZC1T,King,Seattle,WA,98121.0,2026,LAMBORGHINI,TEMERARIO,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,NaN,290999012,CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)
152892,ZHWUC1ZM6S,Yakima,Naches,WA,98937.0,2025,LAMBORGHINI,REVUELTO,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,NaN,290918974,PACIFICORP
158449,ZHWUC1ZM6S,King,Bellevue,WA,98006.0,2025,LAMBORGHINI,REVUELTO,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,NaN,290114653,PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)
160021,ZHWUC1ZM5S,King,Sammamish,WA,98075.0,2025,LAMBORGHINI,REVUELTO,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,NaN,287644927,PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)
183733,ZHWUC1ZM5S,Snohomish,Snohomish,WA,98296.0,2025,LAMBORGHINI,REVUELTO,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,NaN,277331204,PUGET SOUND ENERGY INC
226006,ZHWUC1ZM7T,Pierce,Gig Harbor,WA,98332.0,2026,LAMBORGHINI,REVUELTO,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,NaN,287518913,BONNEVILLE POWER ADMINISTRATION||CITY OF TACOM...
239641,ZHWUC1ZM9S,Spokane,Spokane,WA,99005.0,2025,LAMBORGHINI,REVUELTO,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,NaN,284839649,BONNEVILLE POWER ADMINISTRATION||INLAND POWER ...

All these seem like valid needed rows from Washington State counties. So, we will keep them and replace the nulls with the median value for the make and model of the cars.

In [12]:
ev_data[(ev_data['Make']=='LAMBORGHINI') & (ev_data['Model'].isin(['REVUELTO', 'TEMERARIO'])) & (ev_data['Electric Range'].notna())]

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,DOL Vehicle ID,Electric Utility
210847,ZHWUC1ZM5R,King,Redmond,WA,98053.0,2024,LAMBORGHINI,REVUELTO,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,6.0,275031270,PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)
217733,ZHWUC1ZM9R,Island,Greenbank,WA,98253.0,2024,LAMBORGHINI,REVUELTO,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,6.0,280479489,PUGET SOUND ENERGY INC
227757,ZHWUC1ZM1R,Benton,Richland,WA,99352.0,2024,LAMBORGHINI,REVUELTO,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,6.0,273630752,BONNEVILLE POWER ADMINISTRATION||CITY OF RICHL...
239051,ZHWUC1ZM6R,Spokane,Liberty Lake,WA,99019.0,2024,LAMBORGHINI,REVUELTO,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,6.0,278192862,BONNEVILLE POWER ADMINISTRATION||AVISTA CORP||...
241301,ZHWUC1ZM2R,Pierce,Edgewood,WA,98371.0,2024,LAMBORGHINI,REVUELTO,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,6.0,285809093,PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)

Unfortunately, there is no information regarding electric range for LAMBORGHINI TEMERARIO vehicles. So, we will not be able to replace missing values with make/model mean or median for it. Let us get this information from a valid dataset online and substitute missing value with the information found.

In [13]:
#Fill Electric Range missing values with values found on https://www.lamborghini.com/en-en/models/temerario
ev_data.loc[(ev_data['Electric Range'].isna()) & (ev_data['Make']=='LAMBORGHINI') & (ev_data['Model']=='REVUELTO'), 'Electric Range'] = ev_data.loc[(ev_data['Electric Range'].notna()) & (ev_data['Make']=='LAMBORGHINI') & (ev_data['Model']=='REVUELTO'), 'Electric Range'].mean()
ev_data.loc[(ev_data['Electric Range'].isna()) & (ev_data['Make']=='LAMBORGHINI') & (ev_data['Model']=='TEMERARIO'), 'Electric Range'] = 5

In [14]:
#Call the info and describe method on the revised ev_data again to see a summary of the data
ev_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 285090 entries, 0 to 285821
Data columns (total 13 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   VIN (1-10)                                         285090 non-null  object
 1   County                                             285090 non-null  object
 2   City                                               285090 non-null  object
 3   State                                              285090 non-null  object
 4   Postal Code                                        285090 non-null  float64
 5   Model Year                                         285090 non-null  int64
 6   Make                                               285090 non-null  object
 7   Model                                              285090 non-null  object
 8   Electric Vehicle Type                              285090 non-null  object
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  285090 non-null  object
 10  Electric Range                                     285090 non-null  float64
 11  DOL Vehicle ID                                     285090 non-null  int64
 12  Electric Utility                                   285090 non-null  object
dtypes: float64(2), int64(2), object(9)
memory usage: 30.5+ MB

In [15]:
ev_data.describe()

         Postal Code     Model Year  Electric Range  DOL Vehicle ID
count  285090.000000  285090.000000   285090.000000    2.850900e+05
mean    98276.550935    2022.167070       38.151089    2.479433e+08
std       316.791172       3.067917       77.424947    6.300240e+07
min     98001.000000    1999.000000        0.000000    4.385000e+03
25%     98052.000000    2021.000000        0.000000    2.246288e+08
50%     98133.000000    2023.000000        0.000000    2.650056e+08
75%     98383.000000    2024.000000       32.000000    2.812917e+08
max     99403.000000    2027.000000      337.000000    4.791150e+08

Great! Now, the dataset does not have any missing values.

Let's also check for duplicate rows.

In [16]:
ev_data[ev_data.duplicated()]

Empty DataFrame
Columns: [VIN (1-10), County, City, State, Postal Code, Model Year, Make, Model, Electric Vehicle Type, Clean Alternative Fuel Vehicle (CAFV) Eligibility, Electric Range, DOL Vehicle ID, Electric Utility]
Index: []

In [17]:
#checking for vehicle duplicates using DOL Vehicle ID number since it is the unique vehicle id issued by licensing dept. for identification per our dataset info.
ev_data[ev_data.duplicated(subset=['DOL Vehicle ID'])].sort_values(by=['VIN (1-10)'])

Empty DataFrame
Columns: [VIN (1-10), County, City, State, Postal Code, Model Year, Make, Model, Electric Vehicle Type, Clean Alternative Fuel Vehicle (CAFV) Eligibility, Electric Range, DOL Vehicle ID, Electric Utility]
Index: []

The dataset looks complete without any duplicated rows.

Next, let's standardize the column names.

In [18]:
ev_data.columns=ev_data.columns.str.strip().str.lower().str.replace(" ","_")

In [19]:
ev_data['county']=ev_data['county'].str.strip()

In [20]:
ev_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 285090 entries, 0 to 285821
Data columns (total 13 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   vin_(1-10)                                         285090 non-null  object
 1   county                                             285090 non-null  object
 2   city                                               285090 non-null  object
 3   state                                              285090 non-null  object
 4   postal_code                                        285090 non-null  float64
 5   model_year                                         285090 non-null  int64
 6   make                                               285090 non-null  object
 7   model                                              285090 non-null  object
 8   electric_vehicle_type                              285090 non-null  object
 9   clean_alternative_fuel_vehicle_(cafv)_eligibility  285090 non-null  object
 10  electric_range                                     285090 non-null  float64
 11  dol_vehicle_id                                     285090 non-null  int64
 12  electric_utility                                   285090 non-null  object
dtypes: float64(2), int64(2), object(9)
memory usage: 30.5+ MB

In [21]:
#lets rename vin and cafv fields
ev_data['vin(1-10)']=ev_data['vin_(1-10)']
ev_data['cafv_eligibility'] = ev_data['clean_alternative_fuel_vehicle_(cafv)_eligibility']
ev_data=ev_data.drop(columns = ['vin_(1-10)','clean_alternative_fuel_vehicle_(cafv)_eligibility'])

In [22]:
#Lets ensure county column that will be used as one of our join fields do not have padded spaces
ev_data['county']=ev_data['county'].str.strip()

In [23]:
ev_data['model_year'].unique()

array([2020, 2024, 2014, 2011, 2023, 2026, 2025, 2018, 2019, 2021, 2017,
       2015, 2022, 2016, 2013, 2012, 2027, 2008, 2010, 2000, 2003, 2002,
       1999])

In [24]:
# Lets create 2 new fields, cafv_known and  cafv_eligible_flag (eligible or not)
ev_data['cafv_known'] = ev_data['cafv_eligibility'].isin([
    'Clean Alternative Fuel Vehicle Eligible',
    'Not eligible due to low battery range'
])

ev_data['cafv_true_eligible'] = np.where(
    (ev_data['cafv_eligibility'] == 'Clean Alternative Fuel Vehicle Eligible') |
    ((ev_data['cafv_eligibility'].str.contains('unknown', case=False, na=False)) & 
     (ev_data['electric_vehicle_type'].str.contains('Battery Electric', case=False, na=False))),
    1,
    0
)

Unknown CAFV eligibility values for BEVs have been treated as eligible to correct for missing range-related misclassification.

In [25]:
ev_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 285090 entries, 0 to 285821
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   county                 285090 non-null  object
 1   city                   285090 non-null  object
 2   state                  285090 non-null  object
 3   postal_code            285090 non-null  float64
 4   model_year             285090 non-null  int64
 5   make                   285090 non-null  object
 6   model                  285090 non-null  object
 7   electric_vehicle_type  285090 non-null  object
 8   electric_range         285090 non-null  float64
 9   dol_vehicle_id         285090 non-null  int64
 10  electric_utility       285090 non-null  object
 11  vin(1-10)              285090 non-null  object
 12  cafv_eligibility       285090 non-null  object
 13  cafv_known             285090 non-null  bool
 14  cafv_true_eligible     285090 non-null  int64
dtypes: bool(1), float64(2), int64(3), object(9)
memory usage: 32.9+ MB

In [26]:
ev_data.head()

,county,city,state,postal_code,model_year,make,model,electric_vehicle_type,electric_range,dol_vehicle_id,electric_utility,vin(1-10),cafv_eligibility,cafv_known,cafv_true_eligible
0,King,Shoreline,WA,98133.0,2020,NISSAN,LEAF,Battery Electric Vehicle (BEV),149.0,237906875,CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),1N4AZ1CPXL,Clean Alternative Fuel Vehicle Eligible,True,1
1,Kitsap,Bremerton,WA,98311.0,2024,DODGE,HORNET,Plug-in Hybrid Electric Vehicle (PHEV),32.0,267257532,PUGET SOUND ENERGY INC,ZACPDFDW6R,Clean Alternative Fuel Vehicle Eligible,True,1
2,King,Bellevue,WA,98004.0,2020,TESLA,MODEL Y,Battery Electric Vehicle (BEV),291.0,114986196,PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5YJYGDEE5L,Clean Alternative Fuel Vehicle Eligible,True,1
3,King,Seattle,WA,98178.0,2024,TOYOTA,BZ4X,Battery Electric Vehicle (BEV),0.0,267472859,CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),JTMABACA0R,Eligibility unknown as battery range has not b...,False,1
4,King,Bellevue,WA,98004.0,2014,BMW,I8,Plug-in Hybrid Electric Vehicle (PHEV),14.0,205545868,PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),WBY2Z2C54E,Not eligible due to low battery range,True,0

Let us correct the datatypes for some of the columns next.

In [27]:
#Let's change postal_code and dol_vehicle_id fields to string
ev_data['postal_code'] = ev_data['postal_code'].astype(int).astype(str)
ev_data['dol_vehicle_id'] = ev_data['dol_vehicle_id'].astype(str)

In [28]:
#Let's convert electric_range field to int numeric type
ev_data['electric_range']=ev_data['electric_range'].astype(int)

In [29]:
ev_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 285090 entries, 0 to 285821
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   county                 285090 non-null  object
 1   city                   285090 non-null  object
 2   state                  285090 non-null  object
 3   postal_code            285090 non-null  object
 4   model_year             285090 non-null  int64
 5   make                   285090 non-null  object
 6   model                  285090 non-null  object
 7   electric_vehicle_type  285090 non-null  object
 8   electric_range         285090 non-null  int64
 9   dol_vehicle_id         285090 non-null  object
 10  electric_utility       285090 non-null  object
 11  vin(1-10)              285090 non-null  object
 12  cafv_eligibility       285090 non-null  object
 13  cafv_known             285090 non-null  bool
 14  cafv_true_eligible     285090 non-null  int64
dtypes: bool(1), int64(3), object(11)
memory usage: 32.9+ MB

In [30]:
ev_data.electric_vehicle_type.value_counts()

electric_vehicle_type
Battery Electric Vehicle (BEV)            229339
Plug-in Hybrid Electric Vehicle (PHEV)     55751
Name: count, dtype: int64

In [31]:
ev_data.make.value_counts()

make
TESLA                     117031
CHEVROLET                  19645
NISSAN                     16099
FORD                       15604
KIA                        14306
TOYOTA                     12190
BMW                        11660
HYUNDAI                    11045
RIVIAN                      9081
VOLKSWAGEN                  7645
VOLVO                       7529
JEEP                        6514
AUDI                        5984
CHRYSLER                    3653
MERCEDES-BENZ               3392
HONDA                       3220
SUBARU                      3009
CADILLAC                    2586
PORSCHE                     2050
LEXUS                       1778
POLESTAR                    1661
MAZDA                       1569
MITSUBISHI                  1290
MINI                        1232
FIAT                         851
DODGE                        827
LUCID                        780
GMC                          569
GENESIS                      524
LINCOLN                      456
ACURA                        353
LAND ROVER                   228
SMART                        226
JAGUAR                       146
FISKER                       114
ALFA ROMEO                   102
BRIGHTDROP                    54
LAMBORGHINI                   27
RAM                           25
BENTLEY                        9
TH!NK                          6
ROLLS-ROYCE                    5
MULLEN AUTOMOTIVE INC.         4
VINFAST                        4
AZURE DYNAMICS                 3
WHEEGO ELECTRIC CARS           2
ASTON MARTIN                   1
MASERATI                       1
Name: count, dtype: int64

Electric Vehicle dataset looks complete without duplicates. Next, we will import and cleanse our All Vehicles Registration dataset.

### 2.5.2 All Vehicle Registration Dataset<a id='2.5.2_All_Vehicle_Registration_Dataset'></a>

In [32]:
# import country year grain electric vehicle population data csv file
reg_data = pd.read_csv('../data/raw/Passenger_Vehicle_Registrations_by_County_Data.csv')

In [33]:
reg_data.head()

,Fiscal Year,Transaction Date,Transaction County,Residential County,Fuel Type,Primary Use Class,Count
0,2017,1/31/2017,Adams,Adams,Diesel,Passenger Vehicle,1
1,2017,1/31/2017,Adams,Adams,Diesel,Passenger Vehicle,4
2,2017,1/31/2017,Adams,Adams,Gasoline,Passenger Vehicle,558
3,2017,1/31/2017,Adams,Adams,Gasoline,Passenger Vehicle,49
4,2017,1/31/2017,Adams,Adams,Gasoline,Passenger Vehicle,19

Let's go ahead and drop Transaction County and Fiscal Year as we do not need them for our analysis.

In [34]:
reg_data=reg_data.drop(columns=['Fiscal Year','Transaction County'])

Next, let's add transaction year field to ensure join with electric vehicles dataset.

In [35]:
reg_data['Transaction Year']=pd.to_datetime(reg_data['Transaction Date']).dt.year

Residential County should be a valid name within Washington state and not Out of State. Let us drop those records and ensure we have only valid county names.

In [36]:
reg_data=reg_data[reg_data['Residential County']!='Out Of State']

In [37]:
reg_data['Residential County']=reg_data['Residential County'].str.strip()

In [38]:
reg_data['Residential County'].unique()

array(['Adams', 'Benton', 'Franklin', 'Grant', 'Lincoln', 'Pierce',
       'Stevens', 'Whitman', 'Yakima', 'Asotin', 'Columbia', 'Garfield',
       'King', 'Spokane', 'Walla Walla', 'Chelan', 'Clark', 'Cowlitz',
       'Douglas', 'Grays Harbor', 'Island', 'Kitsap', 'Kittitas',
       'Klickitat', 'Lewis', 'Mason', 'Okanogan', 'Pend Oreille',
       'Snohomish', 'Thurston', 'Whatcom', 'Skagit', 'Clallam',
       'Jefferson', 'Pacific', 'San Juan', 'Ferry', 'Skamania',
       'Wahkiakum'], dtype=object)

In [39]:
reg_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 374343 entries, 0 to 388298
Data columns (total 6 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Transaction Date    374343 non-null  object
 1   Residential County  374343 non-null  object
 2   Fuel Type           374343 non-null  object
 3   Primary Use Class   374343 non-null  object
 4   Count               374343 non-null  int64
 5   Transaction Year    374343 non-null  int32
dtypes: int32(1), int64(1), object(4)
memory usage: 18.6+ MB

Next step will be to correct the data types for Transaction Date (to datetime), and Residential County, Fuel Type, Primary Use Class (to category).

In [40]:
reg_data['Transaction Date']=pd.to_datetime(reg_data['Transaction Date'])
reg_data['Residential County']=reg_data['Residential County'].astype('category')
reg_data['Fuel Type']=reg_data['Fuel Type'].astype('category')
reg_data['Primary Use Class']=reg_data['Primary Use Class'].astype('category')

In [41]:
reg_data.describe(include='all')

,Transaction Date,Residential County,Fuel Type,Primary Use Class,Count,Transaction Year
count,374343,374343,374343,374343,374343.000000,374343.000000
unique,NaN,39,5,1,NaN,NaN
top,NaN,King,Gasoline,Passenger Vehicle,NaN,NaN
freq,NaN,22793,199241,374343,NaN,NaN
mean,2021-12-16 16:09:50.166771968,NaN,NaN,NaN,129.263144,2021.430907
min,2017-01-31 00:00:00,NaN,NaN,NaN,1.000000,2017.000000
25%,2019-08-31 00:00:00,NaN,NaN,NaN,1.000000,2019.000000
50%,2022-01-31 00:00:00,NaN,NaN,NaN,2.000000,2022.000000
75%,2024-04-30 00:00:00,NaN,NaN,NaN,10.000000,2024.000000
max,2026-04-30 00:00:00,NaN,NaN,NaN,108275.000000,2026.000000
std,NaN,NaN,NaN,NaN,1811.929843,2.680133

In [42]:
reg_data['Fuel Type'].unique()

['Diesel', 'Gasoline', 'Hybrid', 'Electric', 'Flex Fuel/Gasoline']
Categories (5, object): ['Diesel', 'Electric', 'Flex Fuel/Gasoline', 'Gasoline', 'Hybrid']

In [43]:
reg_data['Count'].unique()

array([    1,     4,   558, ...,  9314,  2124, 11109])

Next step will be to convert all these fields into lower case fields without any spaces for easier querying downstream.

In [44]:
reg_data.columns=reg_data.columns.str.strip().str.lower().str.replace(" ","_")

In [45]:
reg_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 374343 entries, 0 to 388298
Data columns (total 6 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   transaction_date    374343 non-null  datetime64[ns]
 1   residential_county  374343 non-null  category
 2   fuel_type           374343 non-null  category
 3   primary_use_class   374343 non-null  category
 4   count               374343 non-null  int64
 5   transaction_year    374343 non-null  int32
dtypes: category(3), datetime64[ns](1), int32(1), int64(1)
memory usage: 11.1 MB

The dataset looks complete with no null records and all fuel types needed.

We need this dataset to be grouped by transaction year, residential county to get total passenger vehicle annual registrations count  and by fuel type 'electric' for ev annual registrations as shown below.

In [46]:
reg_total = reg_data.groupby(['transaction_year','residential_county'], observed=False)['count'].sum().reset_index()

In [47]:
reg_ev = reg_data[reg_data['fuel_type']=='Electric'].groupby(['transaction_year','residential_county'], observed=False)['count'].sum().reset_index()

#Lets rename count columns from both aggregated datasets to total_electric_vehicles and total_passenger_vehicles

In [48]:
reg_total.rename(columns={'count':'total_registered_vehicles'}, inplace=True)
reg_ev.rename(columns={'count':'registered_electric_vehicles'}, inplace=True)

Next, let's merge these 2 aggregated datasets on 'transaction_year','residential_county'.

In [49]:
reg_total = reg_total.merge(reg_ev, on = ['transaction_year','residential_county'], how='left')

In [50]:
#lets fill in missing ev count data
reg_total['registered_electric_vehicles']=reg_total['registered_electric_vehicles'].fillna(0)

In [51]:
reg_total.head()

,transaction_year,residential_county,total_registered_vehicles,registered_electric_vehicles
0,2017,Adams,13160,5
1,2017,Asotin,13158,10
2,2017,Benton,139034,191
3,2017,Chelan,56589,99
4,2017,Clallam,52495,111

In [52]:
reg_total.describe(include='all')

,transaction_year,residential_county,total_registered_vehicles,registered_electric_vehicles
count,390.000000,390,3.900000e+02,390.000000
unique,NaN,39,NaN,NaN
top,NaN,Adams,NaN,NaN
freq,NaN,10,NaN,NaN
mean,2021.500000,NaN,1.240737e+05,2352.707692
std,2.875971,NaN,2.501319e+05,9686.146251
min,2017.000000,NaN,4.510000e+02,0.000000
25%,2019.000000,NaN,1.402775e+04,46.250000
50%,2021.500000,NaN,3.779150e+04,218.500000
75%,2024.000000,NaN,9.772350e+04,874.500000
max,2026.000000,NaN,1.503246e+06,113056.000000

Next, let's make sure no duplicates exist.

In [53]:
reg_total.duplicated().sum()

np.int64(0)

In [54]:
#lets check how many records exists with 0 electric vehicle registrations
reg_total[reg_total['registered_electric_vehicles']==0]

,transaction_year,residential_county,total_registered_vehicles,registered_electric_vehicles
34,2017,Wahkiakum,2998,0
89,2019,Garfield,1347,0
128,2020,Garfield,1467,0
167,2021,Garfield,1412,0
245,2023,Garfield,1362,0
284,2024,Garfield,1366,0

This dataset also looks good. Lets import and cleanse the socioeconomic + ev charging stations dataset next.

Only 2 counties exist that had no electric vehicles registered in certain years.

### 2.5.3 Socioeconomic & Charging Stations Support Dataset<a id='2.5.3_All_Vehicle_Registration_Dataset'></a>

In [55]:
# import country year grain socioeconomic + ev charging stations data csv file
support_data = pd.read_csv('../data/raw/median_income_population_ev_charging_station_data.csv')

In [56]:
support_data.head()

  county  year  median_income  population  ev_charging_stations
0  Adams  2017          48849       20068                     1
1  Adams  2018          52870       20200                     1
2  Adams  2019          53535       20335                     2
3  Adams  2020          56421       20613                     2
4  Adams  2021          57405       20900                     2

In [57]:
support_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   county                351 non-null    object
 1   year                  351 non-null    int64
 2   median_income         351 non-null    int64
 3   population            351 non-null    int64
 4   ev_charging_stations  351 non-null    int64
dtypes: int64(4), object(1)
memory usage: 13.8+ KB

In [58]:
support_data.describe(include='all')

       county         year  median_income    population  ev_charging_stations
count     351   351.000000     351.000000  3.510000e+02            351.000000
unique     39          NaN            NaN           NaN                   NaN
top     Adams          NaN            NaN           NaN                   NaN
freq        9          NaN            NaN           NaN                   NaN
mean      NaN  2021.000000   69198.074074  1.989430e+05             32.943020
std       NaN     2.585675   15793.344797  4.002627e+05            126.133997
min       NaN  2017.000000   42212.000000  2.263000e+03              0.000000
25%       NaN  2019.000000   57758.000000  2.246100e+04              2.000000
50%       NaN  2021.000000   65943.000000  6.575000e+04              8.000000
75%       NaN  2023.000000   77989.000000  2.007765e+05             20.000000
max       NaN  2025.000000  126124.000000  2.411700e+06           1412.000000

In [59]:
#Lets ensure county column that will be used as one of our join fields do not have padded spaces
support_data['county']=support_data['county'].str.strip()

Let us proceed to steps needed to merge these 3 datasets next. We will first merge ev dataset with vehicle registration dataset.

### 2.6 Merge All Datasets<a id='2.6_Merge_All_Datasets'></a>

Let's first merge registered vehicles dataset with electric vehicles dataset. We need to make sure both datasets have data for the same time period. reg_total has data from January 2017 to April 2026 while ev_data has data ranging from 1999 to 2027. So, we will need to filter out 2026 data from both datasets and also filter out data prior to 2017 from ev_data.

In [60]:
reg_total=reg_total[reg_total['transaction_year']!=2026]

In [61]:
ev_data=ev_data[(ev_data['model_year']>=2017) & (ev_data['model_year']<2026)]

In [62]:
reg_total.describe()

,transaction_year,total_registered_vehicles,registered_electric_vehicles
count,351.000000,3.510000e+02,351.000000
mean,2021.000000,1.328117e+05,2391.843305
std,2.585675,2.605637e+05,9988.667343
min,2017.000000,1.327000e+03,0.000000
25%,2019.000000,1.536900e+04,45.000000
50%,2021.000000,4.981100e+04,213.000000
75%,2023.000000,1.428480e+05,877.500000
max,2025.000000,1.503246e+06,113056.000000

In [63]:
ev_data.describe(include='all')

,county,city,state,postal_code,model_year,make,model,electric_vehicle_type,electric_range,dol_vehicle_id,electric_utility,vin(1-10),cafv_eligibility,cafv_known,cafv_true_eligible
count,243413,243413,243413,243413,243413.000000,243413,243413,243413,243413.000000,243413,243413,243413,243413,243413,243413.000000
unique,39,499,1,577,NaN,44,168,2,NaN,243413,75,14223,3,2,NaN
top,King,Seattle,WA,98052,NaN,TESLA,MODEL Y,Battery Electric Vehicle (BEV),NaN,276374458,PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),7SAYGDEE7P,Eligibility unknown as battery range has not b...,False,NaN
freq,120126,37928,243413,5853,NaN,98573,48820,196353,NaN,1,86359,1207,162510,162510,NaN
mean,NaN,NaN,NaN,NaN,2022.395665,NaN,NaN,NaN,37.781113,NaN,NaN,NaN,NaN,NaN,0.917720
std,NaN,NaN,NaN,NaN,2.175937,NaN,NaN,NaN,79.851461,NaN,NaN,NaN,NaN,NaN,0.274791
min,NaN,NaN,NaN,NaN,2017.000000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000
25%,NaN,NaN,NaN,NaN,2021.000000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,1.000000
50%,NaN,NaN,NaN,NaN,2023.000000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,1.000000
75%,NaN,NaN,NaN,NaN,2024.000000,NaN,NaN,NaN,30.000000,NaN,NaN,NaN,NaN,NaN,1.000000
max,NaN,NaN,NaN,NaN,2025.000000,NaN,NaN,NaN,337.000000,NaN,NaN,NaN,NaN,NaN,1.000000

Next, we will go ahead and aggregate the EV Dataset at county year level to get Annual EV Count, Avg. Electric Range & CAFV Eligibility Rate.

In [64]:
ev_data['bev_range_updated'] = np.where(ev_data['electric_vehicle_type'].str.contains('Battery Electric', case=False, na=False),
    ev_data['electric_range'],
    np.nan)
ev_data['phev_range_updated'] = np.where(ev_data['electric_vehicle_type'].str.contains('Plug-in Hybrid', case=False, na=False),
    ev_data['electric_range'],
    np.nan)

ev_agg= ev_data.groupby(['county','model_year']).agg(
    bev_ratio_within_ev = ('electric_vehicle_type', lambda x : x.str.contains('Battery', case=False, na=False).mean()),
    range_missing_rate = ('electric_range',lambda x : (x==0).mean()),
    cafv_eligibility_rate = ('cafv_true_eligible', 'mean'),
    ev_count_by_model_year = ('dol_vehicle_id','count'),
    bev_avg_range=('bev_range_updated', 'mean'),
    phev_avg_range=('phev_range_updated', 'mean')
    ).reset_index()

In [65]:
print(ev_data[ev_data['model_year'] == 2021]['cafv_eligibility'].value_counts())

cafv_eligibility
Eligibility unknown as battery range has not been researched    15764
Not eligible due to low battery range                            2503
Clean Alternative Fuel Vehicle Eligible                          2475
Name: count, dtype: int64

In [66]:
ev_agg.county.unique()

array(['Adams', 'Asotin', 'Benton', 'Chelan', 'Clallam', 'Clark',
       'Columbia', 'Cowlitz', 'Douglas', 'Ferry', 'Franklin', 'Garfield',
       'Grant', 'Grays Harbor', 'Island', 'Jefferson', 'King', 'Kitsap',
       'Kittitas', 'Klickitat', 'Lewis', 'Lincoln', 'Mason', 'Okanogan',
       'Pacific', 'Pend Oreille', 'Pierce', 'San Juan', 'Skagit',
       'Skamania', 'Snohomish', 'Spokane', 'Stevens', 'Thurston',
       'Wahkiakum', 'Walla Walla', 'Whatcom', 'Whitman', 'Yakima'],
      dtype=object)

Finally, let's merge the 2 datasets.

In [67]:
#merging ev_agg & reg_total datasets
merged_df1 = reg_total.merge(ev_agg, left_on=['residential_county','transaction_year'], right_on=['county','model_year'], how='left')

In [68]:
merged_df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 12 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   transaction_year              351 non-null    int32
 1   residential_county            351 non-null    object
 2   total_registered_vehicles     351 non-null    int64
 3   registered_electric_vehicles  351 non-null    int64
 4   county                        345 non-null    object
 5   model_year                    345 non-null    float64
 6   bev_ratio_within_ev           345 non-null    float64
 7   range_missing_rate            345 non-null    float64
 8   cafv_eligibility_rate         345 non-null    float64
 9   ev_count_by_model_year        345 non-null    float64
 10  bev_avg_range                 341 non-null    float64
 11  phev_avg_range                331 non-null    float64
dtypes: float64(7), int32(1), int64(2), object(2)
memory usage: 31.7+ KB

In [69]:
#Lets replace null ev dataset columns values
merged_df1[['ev_count_by_model_year']]=merged_df1[['ev_count_by_model_year']].fillna(0)
merged_df1.loc[merged_df1['ev_count_by_model_year']==0, ['cafv_eligibility_rate','bev_ratio_within_ev','range_missing_rate']]=0

In [70]:
merged_df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 12 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   transaction_year              351 non-null    int32
 1   residential_county            351 non-null    object
 2   total_registered_vehicles     351 non-null    int64
 3   registered_electric_vehicles  351 non-null    int64
 4   county                        345 non-null    object
 5   model_year                    345 non-null    float64
 6   bev_ratio_within_ev           351 non-null    float64
 7   range_missing_rate            351 non-null    float64
 8   cafv_eligibility_rate         351 non-null    float64
 9   ev_count_by_model_year        351 non-null    float64
 10  bev_avg_range                 341 non-null    float64
 11  phev_avg_range                331 non-null    float64
dtypes: float64(7), int32(1), int64(2), object(2)
memory usage: 31.7+ KB

Let's rename model_year to year and drop the repeated fields transaction_year and residential_county.

In [71]:
merged_df1=merged_df1.drop(columns=['model_year','county'])
merged_df1=merged_df1.rename(columns={'transaction_year':'year', 'residential_county':'county'})

In [72]:
merged_df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   year                          351 non-null    int32
 1   county                        351 non-null    object
 2   total_registered_vehicles     351 non-null    int64
 3   registered_electric_vehicles  351 non-null    int64
 4   bev_ratio_within_ev           351 non-null    float64
 5   range_missing_rate            351 non-null    float64
 6   cafv_eligibility_rate         351 non-null    float64
 7   ev_count_by_model_year        351 non-null    float64
 8   bev_avg_range                 341 non-null    float64
 9   phev_avg_range                331 non-null    float64
dtypes: float64(6), int32(1), int64(2), object(1)
memory usage: 26.2+ KB

Next we will merge the supporting dataset containing population, median_income and ev charging stations count by county and year. This preprocessed support dataset has already been filtered to contain only years from 2017-2025.

In [73]:
merged_df = merged_df1.merge(support_data, on=['county','year'], how='left')

In [74]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   year                          351 non-null    int32
 1   county                        351 non-null    object
 2   total_registered_vehicles     351 non-null    int64
 3   registered_electric_vehicles  351 non-null    int64
 4   bev_ratio_within_ev           351 non-null    float64
 5   range_missing_rate            351 non-null    float64
 6   cafv_eligibility_rate         351 non-null    float64
 7   ev_count_by_model_year        351 non-null    float64
 8   bev_avg_range                 341 non-null    float64
 9   phev_avg_range                331 non-null    float64
 10  median_income                 351 non-null    int64
 11  population                    351 non-null    int64
 12  ev_charging_stations          351 non-null    int64
dtypes: float64(6), int32(1), int64(5), object(1)
memory usage: 34.4+ KB

In [75]:
merged_df.isnull().sum()

year                             0
county                           0
total_registered_vehicles        0
registered_electric_vehicles     0
bev_ratio_within_ev              0
range_missing_rate               0
cafv_eligibility_rate            0
ev_count_by_model_year           0
bev_avg_range                   10
phev_avg_range                  20
median_income                    0
population                       0
ev_charging_stations             0
dtype: int64

Next, we will do feature engineering and create some features and our target variable which will be our ev_adoption_rate.

In [76]:
#EV Adoption Rate -- Target Variable (multiplication by 100 is to get percentage values)
merged_df['ev_adoption_rate']=100*merged_df['registered_electric_vehicles']/merged_df['total_registered_vehicles']

#EV Growth Rate -- Trend Metric (multiplication by 100 is to get percentage values)
merged_df=merged_df.sort_values(['county','year'])
merged_df['ev_growth_rate']=100*merged_df.groupby('county')['registered_electric_vehicles'].transform(lambda x: (x / (x.shift(1) + 1)) - 1)
#Replace any null values with 0
merged_df['ev_growth_rate']=merged_df['ev_growth_rate'].fillna(0)

#Has Growth? Create a binary flag 0 or 1 to indicate if there was growth
merged_df['has_growth']=(merged_df['ev_growth_rate']>0).astype(int)

#New EV Purchase Ratio (multiplication by 100 is to get percentage values)
merged_df['new_ev_purchase_ratio'] = 100*merged_df['ev_count_by_model_year'] / merged_df['registered_electric_vehicles']
merged_df['new_ev_purchase_ratio'] = merged_df['new_ev_purchase_ratio'].replace([np.inf, -np.inf], np.nan).fillna(0)

#EV Adoption Lag -> Will help identify EV Adoption momentum
merged_df=merged_df.sort_values(['county','year'])
merged_df['ev_adoption_lag']=merged_df.groupby('county')['ev_adoption_rate'].shift(1)

#Handle Nulls in EV Adoption lag for first year 2017 as an indicator for modeling downstream
merged_df['lag_missing_flag'] = merged_df['ev_adoption_lag'].isna().astype(int)

#Fill with mean(Ensures linear models do not get distorted)
#mean_value = merged_df['ev_adoption_lag'].mean()
merged_df['ev_adoption_lag'] = merged_df['ev_adoption_lag'].fillna(0)

#High Adoption Indicator -- Target Variable
merged_df['high_adoption']=(merged_df['ev_adoption_rate']>merged_df['ev_adoption_rate'].quantile(0.75)).astype('int')

#Adoption Segment -- for Business Insights
merged_df['adoption_segment']=pd.qcut(merged_df['ev_adoption_rate'], q=3, labels=['low','medium','high'])

#Median Income Per Vehicle
merged_df['income_per_vehicle']=merged_df['median_income']/merged_df['total_registered_vehicles']

#EV Charging Density (multiplication by 100 is to get percentage values)
merged_df['ev_charging_density']=100*merged_df['ev_charging_stations']/merged_df['population']

#EV Charging Density Flag for 0 values
merged_df['has_charging_infrastructure']=(merged_df['ev_charging_stations']>0).astype(int)

#EV Charging Stations Growth
#merged_df['charging_growth']=merged_df.groupby('county')['ev_charging_stations'].transform(lambda x: (x / (x.shift(1) + 1)) - 1)*100.fillna(0)

Note: EV adoption lag feature was constructed using strictly prior-year values to prevent temporal leakage.

Now that we have created the needed features for our downstream analysis, let us validate this merged_df dataset and make sure everything looks good.

In [77]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 351 entries, 0 to 350
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   year                          351 non-null    int32
 1   county                        351 non-null    object
 2   total_registered_vehicles     351 non-null    int64
 3   registered_electric_vehicles  351 non-null    int64
 4   bev_ratio_within_ev           351 non-null    float64
 5   range_missing_rate            351 non-null    float64
 6   cafv_eligibility_rate         351 non-null    float64
 7   ev_count_by_model_year        351 non-null    float64
 8   bev_avg_range                 341 non-null    float64
 9   phev_avg_range                331 non-null    float64
 10  median_income                 351 non-null    int64
 11  population                    351 non-null    int64
 12  ev_charging_stations          351 non-null    int64
 13  ev_adoption_rate              351 non-null    float64
 14  ev_growth_rate                351 non-null    float64
 15  has_growth                    351 non-null    int64
 16  new_ev_purchase_ratio         351 non-null    float64
 17  ev_adoption_lag               351 non-null    float64
 18  lag_missing_flag              351 non-null    int64
 19  high_adoption                 351 non-null    int64
 20  adoption_segment              351 non-null    category
 21  income_per_vehicle            351 non-null    float64
 22  ev_charging_density           351 non-null    float64
 23  has_charging_infrastructure   351 non-null    int64
dtypes: category(1), float64(12), int32(1), int64(9), object(1)
memory usage: 64.9+ KB

In [78]:
merged_df.head()

,year,county,total_registered_vehicles,registered_electric_vehicles,bev_ratio_within_ev,range_missing_rate,cafv_eligibility_rate,ev_count_by_model_year,bev_avg_range,phev_avg_range,...,ev_growth_rate,has_growth,new_ev_purchase_ratio,ev_adoption_lag,lag_missing_flag,high_adoption,adoption_segment,income_per_vehicle,ev_charging_density,has_charging_infrastructure
0,2017,Adams,13160,5,0.000000,0.00,0.666667,3.0,NaN,42.333333,...,0.000000,0,60.000000,0.000000,1,0,low,3.711930,0.004983,1
39,2018,Adams,13742,4,1.000000,0.00,1.000000,8.0,217.875000,NaN,...,-33.333333,0,200.000000,0.037994,0,0,low,3.847329,0.004950,1
78,2019,Adams,13447,7,0.666667,0.00,0.666667,3.0,220.000000,26.000000,...,40.000000,1,42.857143,0.029108,0,0,low,3.981185,0.009835,1
117,2020,Adams,13726,10,1.000000,0.00,1.000000,9.0,287.333333,NaN,...,25.000000,1,90.000000,0.052056,0,0,low,4.110520,0.009703,1
156,2021,Adams,13898,17,0.750000,0.75,0.750000,8.0,0.000000,23.000000,...,54.545455,1,47.058824,0.072854,0,0,low,4.130450,0.009569,1

In [79]:
merged_df.describe()

,year,total_registered_vehicles,registered_electric_vehicles,bev_ratio_within_ev,range_missing_rate,cafv_eligibility_rate,ev_count_by_model_year,bev_avg_range,phev_avg_range,median_income,...,ev_adoption_rate,ev_growth_rate,has_growth,new_ev_purchase_ratio,ev_adoption_lag,lag_missing_flag,high_adoption,income_per_vehicle,ev_charging_density,has_charging_infrastructure
count,351.000000,3.510000e+02,351.000000,351.000000,351.000000,351.000000,351.000000,341.000000,331.000000,351.000000,...,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000
mean,2021.000000,1.328117e+05,2391.843305,0.716940,0.422311,0.853012,693.484330,99.856750,32.421063,69198.074074,...,0.892993,30.571621,0.831909,49.239732,0.653472,0.111111,0.250712,4.358829,0.016208,0.888889
std,2.585675,2.605637e+05,9988.667343,0.188564,0.390064,0.158142,2656.447358,114.577850,7.518188,15793.344797,...,1.109072,26.674495,0.374481,38.404817,0.893526,0.314718,0.434042,8.069189,0.017088,0.314718
min,2017.000000,1.327000e+03,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.000000,42212.000000,...,0.000000,-100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.059766,0.000000,0.000000
25%,2019.000000,1.536900e+04,45.000000,0.666667,0.000000,0.820291,24.000000,0.000000,28.387500,57758.000000,...,0.187158,21.052632,1.000000,29.332028,0.106162,0.000000,0.000000,0.601555,0.004547,1.000000
50%,2021.000000,4.981100e+04,213.000000,0.763780,0.660131,0.885344,86.000000,3.506849,31.750000,65943.000000,...,0.505474,34.615385,1.000000,41.401274,0.331135,0.000000,0.000000,1.436289,0.010577,1.000000
75%,2023.000000,1.428480e+05,877.500000,0.826876,0.787506,0.933333,302.500000,212.547170,35.438330,77989.000000,...,1.152407,44.346843,1.000000,56.783537,0.829273,0.000000,0.500000,4.120485,0.022868,1.000000
max,2025.000000,1.503246e+06,113056.000000,1.000000,1.000000,1.000000,31048.000000,312.750000,97.000000,126124.000000,...,7.584261,101.176471,1.000000,350.000000,6.437820,1.000000,1.000000,53.364732,0.113208,1.000000

BEV average range median is 3.5 which is very low. Let us look at this field further.

In [80]:
merged_df.groupby('year')['bev_avg_range'].mean()

year
2017    199.378200
2018    214.111083
2019    214.279066
2020    279.027730
2021      5.065739
2022      0.000000
2023      0.000000
2024      0.344566
2025      0.000000
Name: bev_avg_range, dtype: float64

This looks like a data issue. As per official Data.WA.gov documentation, electric range tracking was administratively sunsetted/stopped after 2020 for 
Battery Electric Vehicles (BEVs), justifying the omission of raw range tracking features in this modeling pipeline. We will drop this field as it will not be usable for modeling. Since, bev_avg_range will be dropped, phev_avg_range,range_missing_rate will not be of much use either since we would have wanted to do a comparison. So, we will go ahead and drop all 3 fields.

In [81]:
merged_df=merged_df.drop(columns = ['bev_avg_range', 'phev_avg_range', 'range_missing_rate'])

In [82]:
merged_df.isnull().sum()

year                            0
county                          0
total_registered_vehicles       0
registered_electric_vehicles    0
bev_ratio_within_ev             0
cafv_eligibility_rate           0
ev_count_by_model_year          0
median_income                   0
population                      0
ev_charging_stations            0
ev_adoption_rate                0
ev_growth_rate                  0
has_growth                      0
new_ev_purchase_ratio           0
ev_adoption_lag                 0
lag_missing_flag                0
high_adoption                   0
adoption_segment                0
income_per_vehicle              0
ev_charging_density             0
has_charging_infrastructure     0
dtype: int64

There are no nulls so we are good.
ev_count_by_model_year is a redundant field since we have already captured it in new_ev_purchase_ratio field. So, we will go ahead and drop it as well.

In [83]:
merged_df=merged_df.drop(columns = ['ev_count_by_model_year'])

In [84]:
merged_df[merged_df['ev_adoption_lag'].isna()]

Empty DataFrame
Columns: [year, county, total_registered_vehicles, registered_electric_vehicles, bev_ratio_within_ev, cafv_eligibility_rate, median_income, population, ev_charging_stations, ev_adoption_rate, ev_growth_rate, has_growth, new_ev_purchase_ratio, ev_adoption_lag, lag_missing_flag, high_adoption, adoption_segment, income_per_vehicle, ev_charging_density, has_charging_infrastructure]
Index: []

In [85]:
merged_df[['county','year']].duplicated().sum()

np.int64(0)

In [86]:
merged_df['county'].nunique()

39

In [87]:
merged_df.groupby(['county'])['year'].nunique().sort_values()

county
Adams           9
Asotin          9
Benton          9
Chelan          9
Clallam         9
Clark           9
Columbia        9
Cowlitz         9
Douglas         9
Ferry           9
Franklin        9
Garfield        9
Grant           9
Grays Harbor    9
Island          9
Jefferson       9
King            9
Kitsap          9
Kittitas        9
Klickitat       9
Lewis           9
Lincoln         9
Mason           9
Okanogan        9
Pacific         9
Pend Oreille    9
Pierce          9
San Juan        9
Skagit          9
Skamania        9
Snohomish       9
Spokane         9
Stevens         9
Thurston        9
Wahkiakum       9
Walla Walla     9
Whatcom         9
Whitman         9
Yakima          9
Name: year, dtype: int64

In [88]:
merged_df[merged_df['total_registered_vehicles']==0]

Empty DataFrame
Columns: [year, county, total_registered_vehicles, registered_electric_vehicles, bev_ratio_within_ev, cafv_eligibility_rate, median_income, population, ev_charging_stations, ev_adoption_rate, ev_growth_rate, has_growth, new_ev_purchase_ratio, ev_adoption_lag, lag_missing_flag, high_adoption, adoption_segment, income_per_vehicle, ev_charging_density, has_charging_infrastructure]
Index: []

In [89]:
merged_df['ev_adoption_rate'].describe()

count    351.000000
mean       0.892993
std        1.109072
min        0.000000
25%        0.187158
50%        0.505474
75%        1.152407
max        7.584261
Name: ev_adoption_rate, dtype: float64

In [90]:
merged_df[merged_df['ev_adoption_rate']>1]

,year,county,total_registered_vehicles,registered_electric_vehicles,bev_ratio_within_ev,cafv_eligibility_rate,median_income,population,ev_charging_stations,ev_adoption_rate,ev_growth_rate,has_growth,new_ev_purchase_ratio,ev_adoption_lag,lag_missing_flag,high_adoption,adoption_segment,income_per_vehicle,ev_charging_density,has_charging_infrastructure
236,2023,Benton,146461,1473,0.798201,0.925450,87992,215500,60,1.005728,50.152905,1,52.817379,0.675466,0,0,high,0.600788,0.027842,1
275,2024,Benton,149184,2118,0.699858,0.880512,80988,217850,63,1.419723,43.690638,1,33.191690,1.005728,0,1,high,0.542873,0.028919,1
314,2025,Benton,148797,2865,0.731602,0.948052,95572,219625,99,1.925442,35.205286,1,16.125654,1.419723,0,1,high,0.642298,0.045077,1
237,2023,Chelan,58703,825,0.860000,0.955000,84430,81500,33,1.405380,51.376147,1,48.484848,0.939016,0,1,high,1.438257,0.040491,1
276,2024,Chelan,58570,1069,0.793103,0.915361,76794,82300,38,1.825166,29.418886,1,29.840973,1.405380,0,1,high,1.311149,0.046173,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,2023,Whatcom,161218,3151,0.843951,0.955619,81432,235800,37,1.954496,42.837715,1,44.335132,1.373335,0,1,high,0.505105,0.015691,1
309,2024,Whatcom,162958,4253,0.709386,0.895307,73149,238000,73,2.609875,34.930203,1,26.052198,1.954496,0,1,high,0.448883,0.030672,1
348,2025,Whatcom,161687,5129,0.750318,0.966879,89614,240500,104,3.172178,20.568876,1,15.305128,2.609875,0,1,high,0.554244,0.043243,1
310,2024,Whitman,23467,293,0.639640,0.873874,64070,48750,15,1.248562,35.648148,1,37.883959,0.917235,0,1,high,2.730217,0.030769,1
349,2025,Whitman,23272,364,0.650794,0.968254,62178,49450,20,1.564111,23.809524,1,17.307692,1.248562,0,1,high,2.671794,0.040445,1

Validation checks are looking good. Lets save the data next.

## 2.7 Save The Data <a id='2.7_Save_The_Data'></a>

In [91]:
# save the data to a new csv file
datapath = '../data/processed'
save_file(merged_df, 'final_ev_info_dataset.csv', datapath)
save_file(reg_data, 'vehicle_registration_data_cleaned.csv', datapath)
save_file(ev_data, 'ev_data_by_vehicle_id_cleaned.csv', datapath)

A file already exists with this name.

Do you want to overwrite? (Y/N) Y

Writing file.  "../data/processed\final_ev_info_dataset.csv"
A file already exists with this name.

Do you want to overwrite? (Y/N) Y

Writing file.  "../data/processed\vehicle_registration_data_cleaned.csv"
A file already exists with this name.

Do you want to overwrite? (Y/N) Y

Writing file.  "../data/processed\ev_data_by_vehicle_id_cleaned.csv"

## 2.8 Summary <a id='2.8_Summary'></a>

2.2 Introduction : Revisited our problem statement and goal of helping accelerate EV adoption based on county adoption rate as the target variable using Washington state data as a case study (electric vehicle, all passenger vehicles registration, socioeconomic and charging stations data).</p>
2.3 Imports: Initialized python libraries to enable all data transformation and aggregation workflows.</p>
2.4 Objectives: Defined our objective to build a reliable target variable, engineer predictive features and ensure no fundamental data issues exist.</p>
2.5.1 EV Dataset: Cleaned, reformatted, validated the dataset and extracted vehicle-level insights (electric range, type mix, clean alternate fuel vehicle (CAFV) eligibility) by model year.</p>
2.5.2 Vehicle Registration Dataset: Cleaned, reformatted, validated the dataset & constructed our target variable of EV adoption rate at county/year level using electric vehicles registration as the numerator and total passenger vehicles registration as the denominator.</p>
2.5.3 Socioeconomic Dataset: Integrated external demographic and infrastructure indicators to understand their role in EV adoption rate.</p>
2.6 Merge Datasets: Created a consolidated county-year level EV adoption analytical dataset ensuring alignment across all data sources.</p> 
2.7 Save Data: Saved the finalized dataset to support reproducibility and downstream analysis.</p> 
2.8 Summary: Delivered a modeling-ready dataset with a well-defined target variable of EV adoption rate and robust feature set capturing technological and socioeconomic drivers of EV adoption. This enables us to do data driven identification of high impact counties for EV infrastructure investments.</p>

### Data Sources & References
* **Vehicle & EV Data:** Washington State Department of Licensing (DOL), 
  "Electric Vehicle Population Data" (Published via Data.WA.gov). 
  *Note on Column Deprecation:* As per official Data.WA.gov documentation, 
  electric range tracking was administratively sunsetted/stopped after 2020 for 
  Battery Electric Vehicles (BEVs), justifying the omission of raw range tracking 
  features in this modeling pipeline.